### PR TITLE
feat: standalone components

### PR DESCRIPTION
**Pull request by herefishyfish**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- [ ] Tests for the changes are included.

## What is the new behavior?

Implements standalone components.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Great work @herefishyfish - I'm thinking we plan to release this with ng 17, what do you think? Since it may introduce a breaking change.

**Comment by edusperoni** [comment]
I believe there are no breaking changes with this. I'm wondering if we can also improve the dialogs as well. I'll take a look into how the CDK dealt with it

**Comment by kyjus25** [comment]
Dang it, didn't make v17. Would love to have this as soon as possible 🙏

**Comment by edusperoni** [comment]
It seems like the commits are now a bit messy, can you rebase it on main?

**Comment by herefishyfish** [comment]
Sorry about that, should be good now. 

I'm unsure if we should be removing the NgIf's from the platform filters in favour of the new control flow syntax - maybe I'll raise that as another PR.

**Comment by kyjus25** [comment]
@edusperoni @NathanWalker Bump on this one, excited for it!

**Pull request merged**
